use Northwind

SELECT * FROM PRODUCTS WHERE CATEGORYID=1009;
SELECT * FROM Categories;
INSERT INTO PRODUCTS(PRODUCTNAME,UnitPrice,CategoryID)
VALUES ('PRODUCTO 1',10,1009);
INSERT INTO PRODUCTS(PRODUCTNAME,UnitPrice,CategoryID)
VALUES ('PRODUCTO 2',10,1009);
INSERT INTO PRODUCTS(PRODUCTNAME,UnitPrice,CategoryID)
VALUES ('PRODUCTO 3',10,1009);

BEGIN TRAN;
DELETE FROM PRODUCTS OUTPUT DELETED.ProductID,DELETED.ProductName,
DELETED.UnitPrice,deleted.CategoryID
WHERE CATEGORYID=1009;
COMMIT;
ROLLBACK;

BEGIN TRAN;
SELECT * FROM CATEGORIES WITH (XLOCK,HOLDLOCK)
WHERE CategoryID=1009;
ROLLBACK;